# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=300)),
                ('product_url', models.URLField()),
                ('description', models.TextField()),
                ('retrieved', models.DateTimeField(auto_now_add=True)),
                ('newest', models.DateTimeField()),
                ('oldest', models.DateTimeField()),
                ('amazon_rating', models.FloatField()),
                ('average_rating', models.FloatField()),
                ('weighted_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('text', models.TextField()),
                ('upvote_count', models.IntegerField(default=0)),
                ('downvote_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('reviewer_url', models.URLField()),
                ('reviewer_name', models.CharField(max_length=128)),
                ('reviewer_rank', models.IntegerField()),
                ('verified', models.FloatField(default=0.0)),
                ('review_age', models.FloatField(default=0.0)),
                ('vote_confidence', models.FloatField(default=0.0)),
                ('text_quality', models.FloatField(default=0.0)),
                ('relative_rank', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
                ('end_timestamp', models.DateTimeField()),
                ('_criteria_weights', models.TextField()),
                ('training_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accurating.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(to='accurating.Review'),
        ),
        migrations.AddField(
            model_name='product',
            name='training_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accurating.TrainingSet'),
        ),
    ]
