# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accurating', '0002_auto_20160408_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weighted_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
