# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accurating', '0003_auto_20160408_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingset',
            options={'get_latest_by': 'end_timestamp'},
        ),
        migrations.AlterField(
            model_name='product',
            name='newest',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='oldest',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
