# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accurating', '0004_auto_20160410_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='uid',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
    ]
