# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accurating', '0005_review_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingset',
            name='training_product',
        ),
        migrations.AddField(
            model_name='trainingset',
            name='training_products',
            field=models.ManyToManyField(to='accurating.Product'),
        ),
    ]
