# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accurating', '0007_remove_product_training_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
