# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accurating', '0008_auto_20160410_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingset',
            name='successful',
            field=models.BooleanField(default=False),
        ),
    ]
