# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accurating', '0009_trainingset_successful'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingset',
            options={},
        ),
    ]
