# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accurating', '0011_auto_20160412_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='training_set',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accurating.TrainingSet'),
        ),
    ]
