# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accurating', '0012_product_training_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='error',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='within_target',
            field=models.BooleanField(default=False),
        ),
    ]
