# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accurating', '0013_auto_20160412_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingset',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
