# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accurating', '0014_trainingset_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='training_set',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accurating.TrainingSet'),
        ),
    ]
